### ISSUE TITLE
Do not add ".pyc" into the version control (Github)

### ISSUE THREAD

**Issue by zhshakib** [choyon-ugv/A.A.E.S#1]
Hello Brother.
I was going through your project, then I noticed that you have commited some ".pyc" file into your repo.

It is not recommend by the community that we add ".pyc" files into our repo because they contain byte code!

[Stackoverflow Answer](https://stackoverflow.com/questions/32110126/should-i-put-pyc-files-under-version-control)

You can read the answer from there and close the issue in the next commit!

Hope to see some great work from you! 

Best Wishes!

**Comment by codebychoyon** [comment]
Thanks Brother.
Working on it and close the issue in the next commit.
